// Generated by gencpp from file image_generator/DetectionArray.msg
// DO NOT EDIT!


#ifndef IMAGE_GENERATOR_MESSAGE_DETECTIONARRAY_H
#define IMAGE_GENERATOR_MESSAGE_DETECTIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <image_generator/Detection.h>

namespace image_generator
{
template <class ContainerAllocator>
struct DetectionArray_
{
  typedef DetectionArray_<ContainerAllocator> Type;

  DetectionArray_()
    : header()
    , camId(0)
    , detections()  {
    }
  DetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , camId(0)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _camId_type;
  _camId_type camId;

   typedef std::vector< ::image_generator::Detection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::image_generator::Detection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::image_generator::DetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_generator::DetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionArray_

typedef ::image_generator::DetectionArray_<std::allocator<void> > DetectionArray;

typedef boost::shared_ptr< ::image_generator::DetectionArray > DetectionArrayPtr;
typedef boost::shared_ptr< ::image_generator::DetectionArray const> DetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_generator::DetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_generator::DetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::image_generator::DetectionArray_<ContainerAllocator1> & lhs, const ::image_generator::DetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.camId == rhs.camId &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::image_generator::DetectionArray_<ContainerAllocator1> & lhs, const ::image_generator::DetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace image_generator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::image_generator::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_generator::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_generator::DetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_generator::DetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_generator::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_generator::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_generator::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "800cf52de8cbec7e2f1b32f57b694b11";
  }

  static const char* value(const ::image_generator::DetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x800cf52de8cbec7eULL;
  static const uint64_t static_value2 = 0x2f1b32f57b694b11ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_generator::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_generator/DetectionArray";
  }

  static const char* value(const ::image_generator::DetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_generator::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header with timestamp and frame_id\n"
"Header header\n"
"\n"
"# Id of camera\n"
"uint32 camId\n"
"\n"
"# List of detections\n"
"Detection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: image_generator/Detection\n"
"# Center of segmentation\n"
"float32 cx\n"
"float32 cy\n"
"\n"
"# Bounding box corners\n"
"float32 x1\n"
"float32 x2\n"
"float32 y1\n"
"float32 y2\n"
"\n"
"# The classification confidences (probabilities)\n"
"float32[] scores\n"
"\n"
"# Enum for the obstacle classification result\n"
"int16   ClassUnclassified = 0 \n"
"int16   ClassUnknownSmall = 1\n"
"int16   ClassUnknownBig = 2\n"
"int16   ClassPedestrian = 3 \n"
"int16   ClassMotorbike = 4\n"
"int16   ClassCar = 5\n"
"int16   ClassTruck = 6\n"
"int16   ClassStructure_Pylon = 7\n"
"int16   ClassStructure_Beacon = 8\n"
"int16   ClassStructure_GuardRail = 9\n"
"int16   ClassStructure_ConcreteBarrier = 10\n"
"int16   ClassUnknown = 15\n"
"int16   ClassBus = 16\n"
"int16   ClassBicycle = 17\n"
"int16   ClassTrafficLight = 18\n"
"int16   ClassTrain = 19\n"
"\n"
"# The obstacle classification with the highest probability.\n"
"#\n"
"int16   classification\n"
;
  }

  static const char* value(const ::image_generator::DetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_generator::DetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.camId);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_generator::DetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_generator::DetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "camId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.camId);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::image_generator::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_GENERATOR_MESSAGE_DETECTIONARRAY_H
